name: Scan Bicep code
on:
  push:
    branches:
      - '**'

permissions:
  id-token: write 
  security-events: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        id: msdo

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@latest
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: github.repository_owner == 'Azure-Samples'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}